Repository rilling/OSMDashboard-Winter-2024-SOEN-6431, pull requests merged in 2024-04, with the labels that each got.

#54 Individual trail/chairlift run statistics and highlighting - Group18
  build.gradle
  settings.gradle
  src/main/java/de/storchp/opentracks/osmplugin/MapSelectionActivity.java
  src/main/java/de/storchp/opentracks/osmplugin/MapsActivity.java
  src/main/java/de/storchp/opentracks/osmplugin/Segment.java
  src/main/java/de/storchp/opentracks/osmplugin/dashboardapi/SegmentFinder.java
  src/main/java/de/storchp/opentracks/osmplugin/dashboardapi/TrackPoint.java
  src/main/java/de/storchp/opentracks/osmplugin/maps/TrailSelectionMapView.java
  src/main/java/de/storchp/opentracks/osmplugin/utils/MapItemAdapter.java
  src/main/java/de/storchp/opentracks/osmplugin/utils/ThemeItemAdapter.java
  src/main/res/drawable/ic_marker_green_pushpin_modern.xml
  src/main/res/drawable/ic_marker_red_pushpin_modern.xml
  src/main/res/drawable/ic_table_border.xml
  src/main/res/layout/map.xml
  src/main/res/values/colors.xml
  src/main/res/values/dimens.xml
  src/main/res/values/integers.xml
  src/main/res/values/strings.xml
Labels: enhancement, high_priority, Group 18, medium_priority

#53 Adding tracking information for Ski Resort Locations
  src/main/java/de/storchp/opentracks/osmplugin/MapsActivity.java
  src/main/java/de/storchp/opentracks/osmplugin/dashboardapi/ChairLift.java
  src/main/java/de/storchp/opentracks/osmplugin/dashboardapi/ChairLiftElements.java
  src/main/java/de/storchp/opentracks/osmplugin/dashboardapi/SkiElements.java
  src/main/java/de/storchp/opentracks/osmplugin/dashboardapi/Track.java
  src/main/java/de/storchp/opentracks/osmplugin/dashboardapi/TrackPoint.java
  src/main/java/de/storchp/opentracks/osmplugin/dashboardapi/Trail.java
  src/main/java/de/storchp/opentracks/osmplugin/dashboardapi/Waypoint.java
Labels: Group 16

#72 Main branch compilation fixes, Code smells removed
  src/main/java/de/storchp/opentracks/osmplugin/AggregateDailyData.java
  src/main/java/de/storchp/opentracks/osmplugin/MapsActivity.java
  src/main/java/de/storchp/opentracks/osmplugin/dashboardapi/TrackPoint.java
Labels: bugfix
